- api/application_resource.py
- api/base_resource.py
- api/customer_resource.py
- api/unit.py
- e2e_tests/customer_test.py
- models/__init__.py
- models/application.py
- models/codecs.py
- models/customer.py
implementation of Customers resource, both individual and business customers
supports update, get and list
> implementation of Customer resource

- api/account_resource.py
- api/base_resource.py
- api/unit.py
- e2e_tests/account_test.py
- models/__init__.py
- models/account.py
- models/application.py
- models/codecs.py
implemented depositAccount resource, we are going to add batchAccount in the near future.
added tests to the methods.
Future:
maybe relocate is_20x method
maybe add generic method that returns UnitResponse[T] or UnirError
> DepositAccount 

- api/transaction_resource.py
- api/unit.py
- e2e_tests/transaction_test.py
- models/__init__.py
- models/codecs.py
- models/transaction.py
implementation of Transactions resource with tests
https://developers.unit.co/transactions
> implementation of Transactions

- README.md
added colors to README file, ```python``` did the trick.
> update colors in README.md

- e2e_tests/application_test.py
- unit/api/application_resource.py
- unit/api/base_resource.py
- unit/models/application.py
added upload document files with tests
https://developers.unit.co/application-documents/#upload-document
> Upload document files

- e2e_tests/event_test.py
- unit/api/event_resource.py
fire method was missing event_id
> fix fire event

- unit/models/account.py
- unit/models/application.py
- unit/models/applicationForm.py
- unit/models/card.py
- unit/models/customer.py
- unit/models/event.py
- unit/models/institution.py
- unit/models/transaction.py
from_json_api() small fix.
Our object (such as Address, Phone and etc.) should be transform from json attributes as:
Address.from_json_api(attributes.get("address"))
> from json api() to object

- unit/models/transaction.py
> trace number is optional

- e2e_tests/customer_test.py
> improved tests for Customer

- e2e_tests/api_token_test.py
- unit/__init__.py
- unit/api/api_token_resource.py
- unit/models/api_token.py
- unit/models/codecs.py
implementation of API Token with tests
https://developers.unit.co/org-api-tokens
> implementation of API Token with tests

- e2e_tests/authorization_test.py
- unit/__init__.py
- unit/api/authorization_resource.py
- unit/models/authorization.py
- unit/models/codecs.py
implementation of Authorization resource with tests
https://developers.unit.co/cards-authorizations
> Authorization

- e2e_tests/authorization_request_test.py
- unit/__init__.py
- unit/api/authorization_request_resource.py
- unit/api/authorization_resource.py
- unit/models/authorization_request.py
- unit/models/codecs.py
implementation of AuthorizationRequests resource, with tests
https://docs.unit.co/cards-authorization-requests
> Authorization Requests

- e2e_tests/account_end_of_day_test.py
- unit/__init__.py
- unit/api/account_end_of_day_resource.py
- unit/models/account_end_of_day.py
- unit/models/codecs.py
implementation of AccountEndOfDay resource
https://docs.unit.co/deposit-accounts#get-account-balance-history
> AccountEndOfDay

- e2e_tests/webhook_test.py
- unit/api/webhook_resource.py
added verification function to unit webhooks
https://github.com/unit-finance/unit-python-sdk/issues/19
https://docs.unit.co/webhooks#securing-your-webhooks
> Webhook validation tool

- unit/api/base_resource.py
https://github.com/unit-finance/unit-python-sdk/issues/1
> added user-agent

- setup.py
- unit/models/__init__.py
> fix - create FullName

- .gitignore
- unit/api/account_resource.py
- unit/api/transaction_resource.py
- unit/models/codecs.py
- unit/models/payment.py
* Adds `customer_id` filter for `accounts.list`
* Adds `customer_id` and `account_id` filter to `transactions.list`
* Fixes bug in `Counterparty` codecs
* Fixes bug with `CreatePaymentRequest` : Conflict on request class (now `CreatePaymentBaseRequest`) and Union type.
> Filter Improvements and Bug Fix on CreatePayment

- unit/api/counterparty_resource.py
- unit/models/codecs.py
- unit/models/counterparty.py
https://developers.unit.co/payments-counterparties/#get-counterparty-balance
> Get Counterparty Balance

- e2e_tests/card_test.py
- unit/api/card_resource.py
- unit/models/card.py
- unit/models/codecs.py
https://developers.unit.co/cards/#get-pin-status
> Get pin status

- e2e_tests/card_test.py
- unit/api/card_resource.py
- unit/models/__init__.py
- unit/models/card.py
- unit/models/codecs.py
https://developers.unit.co/cards#card-limits
> added card limits

- setup.py
- unit/api/account_resource.py
- unit/models/account.py
> Account params

- unit/models/codecs.py
- unit/models/event.py
added new event and small fix to authorization request pending event,
approvedAmount is no longer an attribute
> account.reopened event

- setup.py
- unit/api/account_resource.py
- unit/api/application_resource.py
- unit/api/statement_resource.py
- unit/models/__init__.py
- unit/models/account.py
- unit/models/application.py
- unit/models/counterparty.py
- unit/models/customerToken.py
- unit/models/payment.py
- unit/models/transaction.py
Just a few small patches that were needed to run the SDK on our project. 
- Pip was throwing an error when I updated the `version` to `0.7.4` in the `setup.py` file. I must have missed updating the value somewhere... Best I leave the version identification to you guys!
> MazumaGo Integration Patches

- unit/models/application.py
Tag support for createIndividualApplicationDTO
> tags for individualApplicationDTO

- unit/models/codecs.py
- unit/models/transaction.py
Thir PR contains:
- new [Payment Advance Transaction](https://developers.unit.co/resources#transaction-payment-advance)
- new [Repaid Payment Advance Transaction](https://developers.unit.co/resources#transaction-repaid-payment-advance)
- few changes to existed transactions
> Payment Advance and Repaid Payment Advance Transactions

- e2e_tests/counterparty_test.py
- e2e_tests/transaction_test.py
- unit/models/counterparty.py
https://github.com/unit-finance/unit-python-sdk/issues/96
added fields that were missing
added tests
> added fields and tests

- e2e_tests/transaction_test.py
- unit/models/transaction.py
Added attributes to some Transactions according to the issues:
- https://github.com/unit-finance/unit-python-sdk/issues/95
- https://github.com/unit-finance/unit-python-sdk/issues/97
- https://github.com/unit-finance/unit-python-sdk/issues/101
- https://github.com/unit-finance/unit-python-sdk/issues/102
- https://github.com/unit-finance/unit-python-sdk/issues/103
- https://github.com/unit-finance/unit-python-sdk/issues/104
bugs that were fixed:
- https://github.com/unit-finance/unit-python-sdk/issues/94
- https://github.com/unit-finance/unit-python-sdk/issues/98
- https://github.com/unit-finance/unit-python-sdk/issues/99
also, I've added another type of tests in order to check our DTOs.
> Missing attributes in Transactions

- unit/api/received_payment_resource.py
- unit/models/codecs.py
- unit/models/payment.py
implementation of https://docs.unit.co/received-ach#received-payment
> Received Payments

- e2e_tests/counterparty_test.py
- unit/models/__init__.py
https://github.com/unit-finance/unit-python-sdk/issues/107
> add Code to UnitError

- e2e_tests/transaction_test.py
- unit/models/codecs.py
- unit/models/transaction.py
PaymentCanceledTransactionDTO
ChargebackDTO
RewardDTO
https://github.com/unit-finance/unit-python-sdk/issues/112
> Missing transaction types

- e2e_tests/customer_test.py
- unit/models/__init__.py
- unit/models/customer.py
added new fields to Customers and  added a fix to AuthorizedUser.from_json_api()
with tests to the struct
> New fields to Customers

- unit/models/authorization.py
https://github.com/unit-finance/unit-python-sdk/issues/113
> added fields to AuthorizationDTO

- e2e_tests/account_test.py
- e2e_tests/card_test.py
- unit/models/__init__.py
- unit/models/codecs.py
I've created UnitDTO class that every new type we will create will extend it and implement to_dict method.
I've also created new JSON encoder that will be suitable if all of our current and future types
> new JSON encoder

- unit/models/payment.py
Counterparty attribute should be initialized with Counterparty.from_json_api
> fix AchPaymentDTO to use counterparty

- e2e_tests/dispute_test.py
- e2e_tests/payment_test.py
- unit/models/check_deposit.py
- unit/models/dispute.py
- unit/models/payment.py
- unit/utils/date_utils.py
There were some places that date field was datetime. 
- I've made some small fixes to payments and disputes
- string to date
- added some tests
> date and datetime 

- e2e_tests/application_test.py
- e2e_tests/customerToken_test.py
- unit/models/application.py
- unit/models/customerToken.py
added jwtSubject to create_token and create individual application, also I've added jwt_subject field to the tests
> Create Customer Token with JWT

- unit/models/__init__.py
- unit/models/authorization.py
- unit/models/authorization_request.py
- unit/models/transaction.py
small fix to Merchant, could be None
> Merchant is Optional

- e2e_tests/account_test.py
- e2e_tests/application_test.py
- e2e_tests/card_test.py
- e2e_tests/helpers/helpers.py
- unit/api/account_resource.py
- unit/api/card_resource.py
- unit/models/__init__.py
- unit/models/account.py
- unit/models/card.py
- unit/models/codecs.py
implemented Credit Accounts and Credit Cards.
added tests for creditAccount, businessCreditCard and businessCreditVirtualCard.
> Credit Accounts and Cards

- unit/api/checkDeposit_resource.py
small fix
https://github.com/unit-finance/unit-python-sdk/issues/160
> upload CheckDeposit returns a CheckDepositDTO

- e2e_tests/account_test.py
- e2e_tests/transaction_test.py
- unit/api/transaction_resource.py
- unit/models/__init__.py
- unit/models/card.py
- unit/models/transaction.py
- CreateCardLimits to CardLevelLimits
- small bug fix in paymentAdvanceTransactionDTO
- added query_params_to_dict method to create params
- added get_by_id_and_account to get transaction
https://github.com/unit-finance/unit-python-sdk/pull/173
> Create Card with limits

- e2e_tests/authorization_test.py
- unit/models/authorization.py
https://docs.unit.co/resources/#authorization
added missing attributes with a test to comapre api_response attributes and dto attributes
https://github.com/unit-finance/unit-python-sdk/issues/166
> added missing attributes to AuthorizationDTO

- unit/models/__init__.py
added Meta object as dictionary to UnitError
https://github.com/unit-finance/unit-python-sdk/issues/184
> Add meta to error

- unit/models/application.py
small fix to document, name is optional
> fix: document name is Optional

- e2e_tests/account_test.py
- unit/api/account_resource.py
- unit/models/account.py
Implemented freeze & unfreeze account and added test cases for the same.
> Add freeze & unfreeze account

- MANIFEST
- unit/app_config.py
add meta to error object
freeze and unfreeze account
fixed tags usage in query parameters
Make sdk to support python 3.7
Repayments
> version 0.20.0

- unit/models/account.py
- unit/models/api_token.py
- unit/models/application.py
- unit/models/applicationForm.py
- unit/models/authorization_request.py
- unit/models/card.py
- unit/models/check_deposit.py
- unit/models/counterparty.py
- unit/models/customer.py
- unit/models/customerToken.py
- unit/models/fee.py
- unit/models/payment.py
- unit/models/received_payment.py
- unit/models/returnAch.py
- unit/models/reward.py
- unit/models/webhook.py
https://github.com/unit-finance/unit-python-sdk/issues/188
> add return statement to repr functions

- unit/api/checkDeposit_resource.py
https://github.com/unit-finance/unit-python-sdk/issues/194
https://docs.unit.co/check-deposits/#confirm-check-deposit-details
> Confirm Check-Deposit

- e2e_tests/reward_test.py
- unit/models/reward.py
added a test to create a reward with a funding account
https://github.com/unit-finance/unit-python-sdk/issues/170
> Create Reward with Funding Account - bug fix

- unit/api/card_resource.py
- unit/models/card.py
- unit/models/codecs.py
https://github.com/unit-finance/unit-python-sdk/issues/190
https://guides.unit.co/partnerships/astra/#enable-card-to-card-payments-using-astra
> Enable Card To Card Payments Using Astra

- e2e_tests/application_test.py
- unit/api/application_resource.py
- unit/models/application.py
cancel application with test
https://github.com/unit-finance/unit-python-sdk/issues/202
> Cancel Application

- unit/models/payment.py
addenda attribute added to create payments
> add addenda to create AchPayments

- e2e_tests/account_test.py
- e2e_tests/application_test.py
- e2e_tests/helpers/helpers.py
- unit/models/application.py
- unit/utils/date_utils.py
fix year_of_incorporation, created to_year function
added year_of_incorporation to test
thanks: [stephenhutchens1](https://github.com/stephenhutchens1)
> fix: yearOfIncorporation

- e2e_tests/account_test.py
- unit/models/account.py
- unit/models/codecs.py
added CreditLimits for CreditAccounts
with a test
> feat: Credit Account Limits

- e2e_tests/applicationForm_test.py
- e2e_tests/helpers/helpers.py
- unit/models/applicationForm.py
> create applicationForm for existed application

- e2e_tests/transaction_test.py
- unit/models/transaction.py
description is optional, with a test
> fix: WireTransaction 

- e2e_tests/payment_test.py
- unit/api/payment_resource.py
- unit/models/codecs.py
- unit/models/payment.py
https://docs.unit.co/payments#bulk-payments
> Create Bulk Payments

- e2e_tests/payment_test.py
- unit/api/payment_resource.py
create deposit account, simulate incoming wire payment (Sandbox), create inline ach payment and cancel it
> Cancel Ach Payment

- .github/workflows/CI-appsec-blackduck-master.yml
- .github/workflows/CI-appsec-blackduck-pr.yml
As we did with unit-web-sdk earlier, we are also integrating Black Duck into this repo.
The initial PR check will fail, but it will pass after merging and running the scan on master.
> DSO-630-blackduck-unit-python-sdk-init

- unit/models/counterparty.py
CreditOnly added
https://github.com/unit-finance/unit-python-sdk/issues/245
> Counterparty Permissions

- e2e_tests/application_test.py
- unit/models/__init__.py
- unit/models/application.py
small changes to Officer and EntityType
added tags and idempotencyKey to createBusinessApplication
> Small Application Refactoring 

- unit/models/payment.py
add clearingDaysOverride field to create ach payment
> clearingDaysOverride field

- unit/models/account.py
> update close reason

- e2e_tests/statement_test.py
- unit/api/statement_resource.py
> Get Statement HTML and PDF

- e2e_tests/check_payment_test.py
- e2e_tests/helpers/helpers.py
- unit/__init__.py
- unit/api/check_payment_resource.py
- unit/models/__init__.py
- unit/models/check_payment.py
- unit/models/codecs.py
implementation of CheckPayments
> CheckPayments

- e2e_tests/api_token_test.py
- unit/models/api_token.py
added RestrictedResources to CreateAPITokenRequest
https://github.com/unit-finance/unit-python-sdk/issues/257
> CreateAPITokenRequest with RestrictedResources

- README.md
Update readme to correct the date format for birthday when create business application
> Correct guide to create business application

- e2e_tests/fee_test.py
**Changes**
- Fee test now properly adds funds to the created account before creating a fee
> Fee test fixes

- setup.py
- unit/utils/configuration.py
**Changes**
- Version bump to 1.0.1
> Version upgrade to 1.0.1

- e2e_tests/authorization_test.py
- setup.py
- unit/utils/configuration.py
**Changes**
- Version upgrade to 1.0.2
- Fixed test_list_with_wrong_parameters test
> Version upgrade to 1.0.2
